main: ParticleCommand
author: JD1992
version: ${project.version}
name: ParticleCommand
depend: [Vault]
commands:
  particles:
    description: Hauptcommand für das Plugin
    usage: /particles
  particle:
    description: Aufruf der Effektauswahl
    usage: /particle